"use client";

import { Book, ProjectionRow } from "@/types";

interface DownloadButtonsProps {
  book: Book;
  rows: ProjectionRow[];
  wpm: number;
  wpp: number;
  totalPages: number;
}

function formatDateForExport(iso: string): string {
  if (!iso) return "N/A";
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export default function DownloadButtons({
  book,
  rows,
  wpm,
  wpp,
  totalPages,
}: DownloadButtonsProps) {
  // ─── CSV Download ──────────────────────────────────────

  function downloadCSV() {
    const header = "Hours/Day,Pages/Day,Days to Finish,Total Hours,Finish Date";
    const csvRows = rows.map(
      (r) =>
        `${r.hoursPerDay},${r.pagesPerDay},${r.daysToFinish},${r.totalHours},${formatDateForExport(r.finishDate)}`
    );

    const meta = [
      `# ReadReceipt - Reading Projection`,
      `# Book: ${book.title}`,
      `# Author(s): ${book.authors.join(", ")}`,
      `# Pages: ${totalPages}`,
      `# Reading Speed: ${wpm} wpm (${wpp} words/page)`,
      `# Generated: ${new Date().toLocaleDateString()}`,
      "",
    ];

    const content = [...meta, header, ...csvRows].join("\n");
    const blob = new Blob([content], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `readreceipt-${book.isbn}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  }

  // ─── PDF Download ──────────────────────────────────────

  async function downloadPDF() {
    // Dynamic import to keep bundle small on initial load
    const { jsPDF } = await import("jspdf");
    const autoTable = (await import("jspdf-autotable")).default;

    const doc = new jsPDF();

    // Dark background
    doc.setFillColor(13, 13, 13); // --bg #0d0d0d
    doc.rect(0, 0, 210, 297, "F");

    // Title
    doc.setFontSize(20);
    doc.setTextColor(57, 255, 20); // --accent #39FF14
    doc.text("READRECEIPT", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(136, 136, 136); // --fg-muted
    doc.text("// READING PROJECTION MAP", 14, 27);

    // Book info
    doc.setFontSize(14);
    doc.setTextColor(240, 240, 240); // --fg
    doc.text(book.title.toUpperCase(), 14, 40);

    doc.setFontSize(10);
    doc.setTextColor(136, 136, 136);
    doc.text(`by ${book.authors.join(", ")}`, 14, 47);
    doc.text(
      `${totalPages.toLocaleString()} pages | ${wpm} wpm | ${wpp} words/page`,
      14,
      53
    );

    // Table
    autoTable(doc, {
      startY: 60,
      head: [["Hours/Day", "Pages/Day", "Days to Finish", "Total Hours", "Finish Date"]],
      body: rows.map((r) => [
        `${r.hoursPerDay}h`,
        r.pagesPerDay.toString(),
        `${r.daysToFinish} days`,
        `${r.totalHours}h`,
        formatDateForExport(r.finishDate),
      ]),
      theme: "grid",
      headStyles: {
        fillColor: [57, 255, 20],   // --accent
        textColor: [0, 0, 0],       // black text on accent
        fontStyle: "bold",
      },
      bodyStyles: {
        fillColor: [26, 26, 26],    // --bg-surface
        textColor: [240, 240, 240], // --fg
      },
      alternateRowStyles: {
        fillColor: [13, 13, 13],    // --bg
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
        lineColor: [51, 51, 51],    // --border
        lineWidth: 0.5,
      },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(136, 136, 136);
    doc.text(
      `Generated by ReadReceipt on ${new Date().toLocaleDateString()}`,
      14,
      pageHeight - 10
    );

    doc.save(`readreceipt-${book.isbn}.pdf`);
  }

  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={downloadCSV}
        className="border-2 border-border bg-bg-surface px-5 py-2 text-sm font-mono font-bold uppercase tracking-wider text-fg hover:border-fg hover:text-accent"
      >
        Download CSV
      </button>
      <button
        onClick={downloadPDF}
        className="border-2 border-accent bg-accent px-5 py-2 text-sm font-mono font-bold uppercase tracking-wider text-black hover:bg-transparent hover:text-accent"
      >
        Download PDF
      </button>
    </div>
  );
}
