"use client";

import { Book, ProjectionRow } from "@/types";

interface DownloadButtonsProps {
  book: Book;
  rows: ProjectionRow[];
  wpm: number;
  wpp: number;
  totalPages: number;
}

function formatDateForExport(iso: string): string {
  if (!iso) return "N/A";
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export default function DownloadButtons({
  book,
  rows,
  wpm,
  wpp,
  totalPages,
}: DownloadButtonsProps) {
  // ─── CSV Download ──────────────────────────────────────

  function downloadCSV() {
    const header = "Hours/Day,Pages/Day,Days to Finish,Finish Date";
    const csvRows = rows.map(
      (r) =>
        `${r.hoursPerDay},${r.pagesPerDay},${r.daysToFinish},${formatDateForExport(r.finishDate)}`
    );

    const meta = [
      `# ReadReceipt - Reading Projection`,
      `# Book: ${book.title}`,
      `# Author(s): ${book.authors.join(", ")}`,
      `# Pages: ${totalPages}`,
      `# Reading Speed: ${wpm} wpm (${wpp} words/page)`,
      `# Generated: ${new Date().toLocaleDateString()}`,
      "",
    ];

    const content = [...meta, header, ...csvRows].join("\n");
    const blob = new Blob([content], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `readreceipt-${book.isbn}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  }

  // ─── PDF Download ──────────────────────────────────────

  async function downloadPDF() {
    // Dynamic import to keep bundle small on initial load
    const { jsPDF } = await import("jspdf");
    const autoTable = (await import("jspdf-autotable")).default;

    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(26, 26, 46); // --accent
    doc.text("ReadReceipt", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128); // --muted
    doc.text("Reading Projection Map", 14, 27);

    // Book info
    doc.setFontSize(14);
    doc.setTextColor(22, 33, 62);
    doc.text(book.title, 14, 40);

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text(`by ${book.authors.join(", ")}`, 14, 47);
    doc.text(
      `${totalPages.toLocaleString()} pages | ${wpm} wpm | ${wpp} words/page`,
      14,
      53
    );

    // Table
    autoTable(doc, {
      startY: 60,
      head: [["Hours/Day", "Pages/Day", "Days to Finish", "Finish Date"]],
      body: rows.map((r) => [
        `${r.hoursPerDay}h`,
        r.pagesPerDay.toString(),
        `${r.daysToFinish} days`,
        formatDateForExport(r.finishDate),
      ]),
      theme: "grid",
      headStyles: {
        fillColor: [22, 33, 62],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: {
        fillColor: [250, 248, 245],
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
      },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by ReadReceipt on ${new Date().toLocaleDateString()}`,
      14,
      pageHeight - 10
    );

    doc.save(`readreceipt-${book.isbn}.pdf`);
  }

  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={downloadCSV}
        className="rounded-lg border border-border bg-surface px-4 py-2 text-sm font-medium hover:bg-accent-light active:scale-[0.98]"
      >
        Download CSV
      </button>
      <button
        onClick={downloadPDF}
        className="rounded-lg border border-accent bg-accent px-4 py-2 text-sm font-medium text-white hover:bg-accent/90 active:scale-[0.98]"
      >
        Download PDF
      </button>
    </div>
  );
}
